### ISSUE TITLE
nextrtc Support multiplayer video?

### ISSUE THREAD

**Issue by wgd12389** [mslosarz/nextrtc-signaling-server#12]
i see the video demo code is mesh architecture, and i haven't see the signaling-server code for support multiplayer video

**Comment by mslosarz** [comment]
I don't understand your question, what do you mean by 'multiplayer video'?

**Comment by wgd12389** [comment]
multiplayer video -> multiplex video

**Comment by mslosarz** [comment]
I've also created broadcast type where there is one broadcaster and audience (I'll deploy this app to examples.nextrtc.org). This solution might be good for one to many conversation (small lecture), but in this approach broadcaster has to have quite good device and wide bandwidth of network connection (because each stream is encrypted separately...).

**Comment by mslosarz** [comment]
I've deployed lastest examples version, now you can try on your own how broadcast in nextRTC works

**Comment by wgd12389** [comment]
examples.nextrtc.org is error page

**Comment by mslosarz** [comment]
My mistake :), Please visit:
https://examples.nextrtc.org/videochat/

**Comment by wgd12389** [comment]
but,i see nextrtc-videochat-with-rest project not support https. if website isn's https, remote visit video-demo ,webrtc Will be reported to the wrong

**Comment by mslosarz** [comment]
please try branches:
https://github.com/mslosarz/nextrtc-videochat-with-rest/tree/social_login_test and
https://github.com/mslosarz/nextrtc-videochat-with-rest/tree/default_ssl
