### ISSUE TITLE
In MeshConversation sometimes newJoined is not sent to all

### ISSUE THREAD

**Issue by jacobhub** [mslosarz/nextrtc-signaling-server#13]
Hi, I am testing nextrtc and I am facing an issue where sometimes 'newJoined' signal is missing, is this a known issue ? any idea why this might happen ?

**Comment by mslosarz** [comment]
Please provide logs (server side + client side) if it issue I'll fix it

1 sty 2017 17:32 "jacobhub" <notifications@github.com> napisał(a):

**Comment by mslosarz** [comment]
I've created new tests, and I'm pretty sure that newJoined is sent to all members of mesh conversation, and to broadcaster. I found that sometimes signal exchange could be faulty because of state of connection. I fixed it today. Your case is probably connected with js client - I'm looking into it now. 
Please be patient :)

**Comment by mslosarz** [comment]
I've check it again and I wasn't able to recreate this issue, please check 0.0.5 version if you still have problems with missing requests.

**Comment by mslosarz** [comment]
added flush to send on remote session solved issue
