### ISSUE TITLE
Is it possible to use nextRTC in mobile using for example ionic or native developing? 

### ISSUE THREAD

**Issue by ManoogD** [mslosarz/nextrtc-signaling-server#19]
Hi! We've reached stage that we need a mobile version of our project. We using nextRTC in our backend development and it works fine with client-browser mode. As we know that noone RTC based frameworks don't work with iOS from browsers (even chrome) that's why we have some questions. We decided to create mobile application, it will be perfect if we use ionic 2 for mobile development because our engineers have experience in that only (we can't create native applications for ios and android because), that's why we would like to hear, at least, your opinion about our idea and possibilities? Is it possible to create mobile working version for android and ios at all? Thanks

**Comment by mslosarz** [comment]
NextRTC is only signalling server. If you want to have streaming on your native app you should look for library which is able to handle WebRTC streams ([here is some demo app](https://github.com/ISBX/apprtc-ios)). In your native app you have to implement client part of signal exchange (so because this part is specific for nextRTC). I think that it is possible to create native app, but please remember that'll cost you a lot of time.
