### ISSUE TITLE
Is nextRTC use a single thread to handle connections ?

### ISSUE THREAD

**Issue by LorenzoMcMaster** [mslosarz/nextrtc-signaling-server#30]
I'm trying to understand the code and I feel that there is a single thread that handle all incoming connections but I'm not sure of it.

I've read carefully the documentation and it's not mentioned anywhere that the server is single threaded or using multiple threads to handle connections.

It would be useful to make the documentation more clear on this point.

Thanks,

**Comment by mslosarz** [comment]
I'll prepare a section in documentation about threading model in NextRTC.


NextRTC is based on java standard websocket implementation, so there should
be one thread per endpoint instance. Endpoint instance is ussualy created
when new connection is opened but it's not a rule. I suspect that each
server has configuration where you can set max number of executors.
Outgoing messages are synchronized on session (server client connection),
but message sender has own pool to process outgoing traffic.

You have to keep that in mind during implementation own signals and event
handlers.


05.02.2018 4:35 PM "LorenzoMcMaster" <notifications@github.com> napisał(a):

I'm trying to understand the cngode and I feel that there is a single
thread that handle all incoming connections but I'm not sure of it.

I've read carefully the documentation and it's not mentioned anywhere that
the server is single threaded or using multiple threads to handle
connections.

It would be useful to make the documentation more clear on this point.

Thanks,

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mslosarz/nextrtc-signaling-server/issues/30>, or mute
the thread

**Comment by mslosarz** [comment]
No longer valid in version RC5 you can decide how you're going to handle connections. :)
